<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesCearaSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['name' => 'Abaiara', 'state_id' => 6],
            ['name' => 'Acarape', 'state_id' => 6],
            ['name' => 'Acaraú', 'state_id' => 6],
            ['name' => 'Acopiara', 'state_id' => 6],
            ['name' => 'Aiuaba', 'state_id' => 6],
            ['name' => 'Alcântaras', 'state_id' => 6],
            ['name' => 'Altaneira', 'state_id' => 6],
            ['name' => 'Alto Santo', 'state_id' => 6],
            ['name' => 'Amontada', 'state_id' => 6],
            ['name' => 'Antonina do Norte', 'state_id' => 6],
            ['name' => 'Apuiarés', 'state_id' => 6],
            ['name' => 'Aquiraz', 'state_id' => 6],
            ['name' => 'Aracati', 'state_id' => 6],
            ['name' => 'Aracoiaba', 'state_id' => 6],
            ['name' => 'Ararendá', 'state_id' => 6],
            ['name' => 'Araripe', 'state_id' => 6],
            ['name' => 'Aratuba', 'state_id' => 6],
            ['name' => 'Arneiroz', 'state_id' => 6],
            ['name' => 'Assaré', 'state_id' => 6],
            ['name' => 'Aurora', 'state_id' => 6],
            ['name' => 'Baixio', 'state_id' => 6],
            ['name' => 'Banabuiú', 'state_id' => 6],
            ['name' => 'Barbalha', 'state_id' => 6],
            ['name' => 'Barreira', 'state_id' => 6],
            ['name' => 'Barro', 'state_id' => 6],
            ['name' => 'Barroquinha', 'state_id' => 6],
            ['name' => 'Baturité', 'state_id' => 6],
            ['name' => 'Beberibe', 'state_id' => 6],
            ['name' => 'Bela Cruz', 'state_id' => 6],
            ['name' => 'Boa Viagem', 'state_id' => 6],
            ['name' => 'Brejo Santo', 'state_id' => 6],
            ['name' => 'Camocim', 'state_id' => 6],
            ['name' => 'Campos Sales', 'state_id' => 6],
            ['name' => 'Canindé', 'state_id' => 6],
            ['name' => 'Capistrano', 'state_id' => 6],
            ['name' => 'Caridade', 'state_id' => 6],
            ['name' => 'Cariré', 'state_id' => 6],
            ['name' => 'Caririaçu', 'state_id' => 6],
            ['name' => 'Cariús', 'state_id' => 6],
            ['name' => 'Carnaubal', 'state_id' => 6],
            ['name' => 'Cascavel', 'state_id' => 6],
            ['name' => 'Catarina', 'state_id' => 6],
            ['name' => 'Catunda', 'state_id' => 6],
            ['name' => 'Caucaia', 'state_id' => 6],
            ['name' => 'Cedro', 'state_id' => 6],
            ['name' => 'Chaval', 'state_id' => 6],
            ['name' => 'Choró', 'state_id' => 6],
            ['name' => 'Chorozinho', 'state_id' => 6],
            ['name' => 'Coreaú', 'state_id' => 6],
            ['name' => 'Crateús', 'state_id' => 6],
            ['name' => 'Crato', 'state_id' => 6],
            ['name' => 'Croatá', 'state_id' => 6],
            ['name' => 'Cruz', 'state_id' => 6],
            ['name' => 'Deputado Irapuan Pinheiro', 'state_id' => 6],
            ['name' => 'Ererê', 'state_id' => 6],
            ['name' => 'Eusébio', 'state_id' => 6],
            ['name' => 'Farias Brito', 'state_id' => 6],
            ['name' => 'Forquilha', 'state_id' => 6],
            ['name' => 'Fortaleza', 'state_id' => 6],
            ['name' => 'Fortim', 'state_id' => 6],
            ['name' => 'Frecheirinha', 'state_id' => 6],
            ['name' => 'General Sampaio', 'state_id' => 6],
            ['name' => 'Graça', 'state_id' => 6],
            ['name' => 'Granja', 'state_id' => 6],
            ['name' => 'Granjeiro', 'state_id' => 6],
            ['name' => 'Groaíras', 'state_id' => 6],
            ['name' => 'Guaiúba', 'state_id' => 6],
            ['name' => 'Guaraciaba do Norte', 'state_id' => 6],
            ['name' => 'Guaramiranga', 'state_id' => 6],
            ['name' => 'Hidrolândia', 'state_id' => 6],
            ['name' => 'Horizonte', 'state_id' => 6],
            ['name' => 'Ibaretama', 'state_id' => 6],
            ['name' => 'Ibiapina', 'state_id' => 6],
            ['name' => 'Ibicuitinga', 'state_id' => 6],
            ['name' => 'Icapuí', 'state_id' => 6],
            ['name' => 'Icó', 'state_id' => 6],
            ['name' => 'Iguatu', 'state_id' => 6],
            ['name' => 'Independência', 'state_id' => 6],
            ['name' => 'Ipaporanga', 'state_id' => 6],
            ['name' => 'Ipaumirim', 'state_id' => 6],
            ['name' => 'Ipu', 'state_id' => 6],
            ['name' => 'Ipueiras', 'state_id' => 6],
            ['name' => 'Iracema', 'state_id' => 6],
            ['name' => 'Irauçuba', 'state_id' => 6],
            ['name' => 'Itaiçaba', 'state_id' => 6],
            ['name' => 'Itaitinga', 'state_id' => 6],
            ['name' => 'Itapagé', 'state_id' => 6],
            ['name' => 'Itapipoca', 'state_id' => 6],
            ['name' => 'Itapiúna', 'state_id' => 6],
            ['name' => 'Itarema', 'state_id' => 6],
            ['name' => 'Itatira', 'state_id' => 6],
            ['name' => 'Jaguaretama', 'state_id' => 6],
            ['name' => 'Jaguaribara', 'state_id' => 6],
            ['name' => 'Jaguaribe', 'state_id' => 6],
            ['name' => 'Jaguaruana', 'state_id' => 6],
            ['name' => 'Jardim', 'state_id' => 6],
            ['name' => 'Jati', 'state_id' => 6],
            ['name' => 'Jijoca de Jericoacoara', 'state_id' => 6],
            ['name' => 'Juazeiro do Norte', 'state_id' => 6],
            ['name' => 'Jucás', 'state_id' => 6],
            ['name' => 'Lavras da Mangabeira', 'state_id' => 6],
            ['name' => 'Limoeiro do Norte', 'state_id' => 6],
            ['name' => 'Madalena', 'state_id' => 6],
            ['name' => 'Maracanaú', 'state_id' => 6],
            ['name' => 'Maranguape', 'state_id' => 6],
            ['name' => 'Marco', 'state_id' => 6],
            ['name' => 'Martinópole', 'state_id' => 6],
            ['name' => 'Massapê', 'state_id' => 6],
            ['name' => 'Mauriti', 'state_id' => 6],
            ['name' => 'Meruoca', 'state_id' => 6],
            ['name' => 'Milagres', 'state_id' => 6],
            ['name' => 'Milhã', 'state_id' => 6],
            ['name' => 'Miraíma', 'state_id' => 6],
            ['name' => 'Missão Velha', 'state_id' => 6],
            ['name' => 'Mombaça', 'state_id' => 6],
            ['name' => 'Monsenhor Tabosa', 'state_id' => 6],
            ['name' => 'Morada Nova', 'state_id' => 6],
            ['name' => 'Moraújo', 'state_id' => 6],
            ['name' => 'Morrinhos', 'state_id' => 6],
            ['name' => 'Mucambo', 'state_id' => 6],
            ['name' => 'Mulungu', 'state_id' => 6],
            ['name' => 'Nova Olinda', 'state_id' => 6],
            ['name' => 'Nova Russas', 'state_id' => 6],
            ['name' => 'Novo Oriente', 'state_id' => 6],
            ['name' => 'Ocara', 'state_id' => 6],
            ['name' => 'Orós', 'state_id' => 6],
            ['name' => 'Pacajus', 'state_id' => 6],
            ['name' => 'Pacatuba', 'state_id' => 6],
            ['name' => 'Pacoti', 'state_id' => 6],
            ['name' => 'Pacujá', 'state_id' => 6],
            ['name' => 'Palhano', 'state_id' => 6],
            ['name' => 'Palmácia', 'state_id' => 6],
            ['name' => 'Paracuru', 'state_id' => 6],
            ['name' => 'Paraipaba', 'state_id' => 6],
            ['name' => 'Parambu', 'state_id' => 6],
            ['name' => 'Paramoti', 'state_id' => 6],
            ['name' => 'Pedra Branca', 'state_id' => 6],
            ['name' => 'Penaforte', 'state_id' => 6],
            ['name' => 'Pentecoste', 'state_id' => 6],
            ['name' => 'Pereiro', 'state_id' => 6],
            ['name' => 'Pindoretama', 'state_id' => 6],
            ['name' => 'Piquet Carneiro', 'state_id' => 6],
            ['name' => 'Pires Ferreira', 'state_id' => 6],
            ['name' => 'Poranga', 'state_id' => 6],
            ['name' => 'Porteiras', 'state_id' => 6],
            ['name' => 'Potengi', 'state_id' => 6],
            ['name' => 'Potiretama', 'state_id' => 6],
            ['name' => 'Quiterianópolis', 'state_id' => 6],
            ['name' => 'Quixadá', 'state_id' => 6],
            ['name' => 'Quixelô', 'state_id' => 6],
            ['name' => 'Quixeramobim', 'state_id' => 6],
            ['name' => 'Quixeré', 'state_id' => 6],
            ['name' => 'Redenção', 'state_id' => 6],
            ['name' => 'Reriutaba', 'state_id' => 6],
            ['name' => 'Russas', 'state_id' => 6],
            ['name' => 'Saboeiro', 'state_id' => 6],
            ['name' => 'Salitre', 'state_id' => 6],
            ['name' => 'Santa Quitéria', 'state_id' => 6],
            ['name' => 'Santana do Acaraú', 'state_id' => 6],
            ['name' => 'Santana do Cariri', 'state_id' => 6],
            ['name' => 'São Benedito', 'state_id' => 6],
            ['name' => 'São Gonçalo do Amarante', 'state_id' => 6],
            ['name' => 'São João do Jaguaribe', 'state_id' => 6],
            ['name' => 'São Luís do Curu', 'state_id' => 6],
            ['name' => 'Senador Pompeu', 'state_id' => 6],
            ['name' => 'Senador Sá', 'state_id' => 6],
            ['name' => 'Sobral', 'state_id' => 6],
            ['name' => 'Solonópole', 'state_id' => 6],
            ['name' => 'Tabuleiro do Norte', 'state_id' => 6],
            ['name' => 'Tamboril', 'state_id' => 6],
            ['name' => 'Tarrafas', 'state_id' => 6],
            ['name' => 'Tauá', 'state_id' => 6],
            ['name' => 'Tejuçuoca', 'state_id' => 6],
            ['name' => 'Tianguá', 'state_id' => 6],
            ['name' => 'Trairi', 'state_id' => 6],
            ['name' => 'Tururu', 'state_id' => 6],
            ['name' => 'Ubajara', 'state_id' => 6],
            ['name' => 'Umari', 'state_id' => 6],
            ['name' => 'Umirim', 'state_id' => 6],
            ['name' => 'Uruburetama', 'state_id' => 6],
            ['name' => 'Uruoca', 'state_id' => 6],
            ['name' => 'Varjota', 'state_id' => 6],
            ['name' => 'Várzea Alegre', 'state_id' => 6],
            ['name' => 'Viçosa do Ceará', 'state_id' => 6]
        ]);

        $this->command->info('Cidades do Ceará importadas com sucesso!');
    }
}