<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesMinasGeraisSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cities')->insert([
        	['name' => 'Abadia dos Dourados', 'state_id' => 13],
            ['name' => 'Abaeté', 'state_id' => 13],
            ['name' => 'Abre Campo', 'state_id' => 13],
            ['name' => 'Acaiaca', 'state_id' => 13],
            ['name' => 'Açucena', 'state_id' => 13],
            ['name' => 'Água Boa', 'state_id' => 13],
            ['name' => 'Água Comprida', 'state_id' => 13],
            ['name' => 'Aguanil', 'state_id' => 13],
            ['name' => 'Águas Formosas', 'state_id' => 13],
            ['name' => 'Águas Vermelhas', 'state_id' => 13],
            ['name' => 'Aimorés', 'state_id' => 13],
            ['name' => 'Aiuruoca', 'state_id' => 13],
            ['name' => 'Alagoa', 'state_id' => 13],
            ['name' => 'Albertina', 'state_id' => 13],
            ['name' => 'Além Paraíba', 'state_id' => 13],
            ['name' => 'Alfenas', 'state_id' => 13],
            ['name' => 'Alfredo Vasconcelos', 'state_id' => 13],
            ['name' => 'Almenara', 'state_id' => 13],
            ['name' => 'Alpercata', 'state_id' => 13],
            ['name' => 'Alpinópolis', 'state_id' => 13],
            ['name' => 'Alterosa', 'state_id' => 13],
            ['name' => 'Alto Caparaó', 'state_id' => 13],
            ['name' => 'Alto Jequitibá', 'state_id' => 13],
            ['name' => 'Alto Rio Doce', 'state_id' => 13],
            ['name' => 'Alvarenga', 'state_id' => 13],
            ['name' => 'Alvinópolis', 'state_id' => 13],
            ['name' => 'Alvorada de Minas', 'state_id' => 13],
            ['name' => 'Amparo do Serra', 'state_id' => 13],
            ['name' => 'Andradas', 'state_id' => 13],
            ['name' => 'Andrelândia', 'state_id' => 13],
            ['name' => 'Angelândia', 'state_id' => 13],
            ['name' => 'Antônio Carlos', 'state_id' => 13],
            ['name' => 'Antônio Dias', 'state_id' => 13],
            ['name' => 'Antônio Prado de Minas', 'state_id' => 13],
            ['name' => 'Araçaí', 'state_id' => 13],
            ['name' => 'Aracitaba', 'state_id' => 13],
            ['name' => 'Araçuaí', 'state_id' => 13],
            ['name' => 'Araguari', 'state_id' => 13],
            ['name' => 'Arantina', 'state_id' => 13],
            ['name' => 'Araponga', 'state_id' => 13],
            ['name' => 'Araporã', 'state_id' => 13],
            ['name' => 'Arapuá', 'state_id' => 13],
            ['name' => 'Araújos', 'state_id' => 13],
            ['name' => 'Araxá', 'state_id' => 13],
            ['name' => 'Arceburgo', 'state_id' => 13],
            ['name' => 'Arcos', 'state_id' => 13],
            ['name' => 'Areado', 'state_id' => 13],
            ['name' => 'Argirita', 'state_id' => 13],
            ['name' => 'Aricanduva', 'state_id' => 13],
            ['name' => 'Arinos', 'state_id' => 13],
            ['name' => 'Astolfo Dutra', 'state_id' => 13],
            ['name' => 'Ataléia', 'state_id' => 13],
            ['name' => 'Augusto de Lima', 'state_id' => 13],
            ['name' => 'Baependi', 'state_id' => 13],
            ['name' => 'Baldim', 'state_id' => 13],
            ['name' => 'Bambuí', 'state_id' => 13],
            ['name' => 'Bandeira', 'state_id' => 13],
            ['name' => 'Bandeira do Sul', 'state_id' => 13],
            ['name' => 'Barão de Cocais', 'state_id' => 13],
            ['name' => 'Barão de Monte Alto', 'state_id' => 13],
            ['name' => 'Barbacena', 'state_id' => 13],
            ['name' => 'Barra Longa', 'state_id' => 13],
            ['name' => 'Barroso', 'state_id' => 13],
            ['name' => 'Bela Vista de Minas', 'state_id' => 13],
            ['name' => 'Belmiro Braga', 'state_id' => 13],
            ['name' => 'Belo Horizonte', 'state_id' => 13],
            ['name' => 'Belo Oriente', 'state_id' => 13],
            ['name' => 'Belo Vale', 'state_id' => 13],
            ['name' => 'Berilo', 'state_id' => 13],
            ['name' => 'Berizal', 'state_id' => 13],
            ['name' => 'Bertópolis', 'state_id' => 13],
            ['name' => 'Betim', 'state_id' => 13],
            ['name' => 'Bias Fortes', 'state_id' => 13],
            ['name' => 'Bicas', 'state_id' => 13],
            ['name' => 'Biquinhas', 'state_id' => 13],
            ['name' => 'Boa Esperança', 'state_id' => 13],
            ['name' => 'Bocaina de Minas', 'state_id' => 13],
            ['name' => 'Bocaiúva', 'state_id' => 13],
            ['name' => 'Bom Despacho', 'state_id' => 13],
            ['name' => 'Bom Jardim de Minas', 'state_id' => 13],
            ['name' => 'Bom Jesus da Penha', 'state_id' => 13],
            ['name' => 'Bom Jesus do Amparo', 'state_id' => 13],
            ['name' => 'Bom Jesus do Galho', 'state_id' => 13],
            ['name' => 'Bom Repouso', 'state_id' => 13],
            ['name' => 'Bom Sucesso', 'state_id' => 13],
            ['name' => 'Bonfim', 'state_id' => 13],
            ['name' => 'Bonfinópolis de Minas', 'state_id' => 13],
            ['name' => 'Bonito de Minas', 'state_id' => 13],
            ['name' => 'Borda da Mata', 'state_id' => 13],
            ['name' => 'Botelhos', 'state_id' => 13],
            ['name' => 'Botumirim', 'state_id' => 13],
            ['name' => 'Brás Pires', 'state_id' => 13],
            ['name' => 'Brasilândia de Minas', 'state_id' => 13],
            ['name' => 'Brasília de Minas', 'state_id' => 13],
            ['name' => 'Brasópolis', 'state_id' => 13],
            ['name' => 'Braúnas', 'state_id' => 13],
            ['name' => 'Brumadinho', 'state_id' => 13],
            ['name' => 'Bueno Brandão', 'state_id' => 13],
            ['name' => 'Buenópolis', 'state_id' => 13],
            ['name' => 'Bugre', 'state_id' => 13],
            ['name' => 'Buritis', 'state_id' => 13],
            ['name' => 'Buritizeiro', 'state_id' => 13],
            ['name' => 'Cabeceira Grande', 'state_id' => 13],
            ['name' => 'Cabo Verde', 'state_id' => 13],
            ['name' => 'Cachoeira da Prata', 'state_id' => 13],
            ['name' => 'Cachoeira de Minas', 'state_id' => 13],
            ['name' => 'Cachoeira de Pajeú', 'state_id' => 13],
            ['name' => 'Cachoeira Dourada', 'state_id' => 13],
            ['name' => 'Caetanópolis', 'state_id' => 13],
            ['name' => 'Caeté', 'state_id' => 13],
            ['name' => 'Caiana', 'state_id' => 13],
            ['name' => 'Cajuri', 'state_id' => 13],
            ['name' => 'Caldas', 'state_id' => 13],
            ['name' => 'Camacho', 'state_id' => 13],
            ['name' => 'Camanducaia', 'state_id' => 13],
            ['name' => 'Cambuí', 'state_id' => 13],
            ['name' => 'Cambuquira', 'state_id' => 13],
            ['name' => 'Campanário', 'state_id' => 13],
            ['name' => 'Campanha', 'state_id' => 13],
            ['name' => 'Campestre', 'state_id' => 13],
            ['name' => 'Campina Verde', 'state_id' => 13],
            ['name' => 'Campo Azul', 'state_id' => 13],
            ['name' => 'Campo Belo', 'state_id' => 13],
            ['name' => 'Campo do Meio', 'state_id' => 13],
            ['name' => 'Campo Florido', 'state_id' => 13],
            ['name' => 'Campos Altos', 'state_id' => 13],
            ['name' => 'Campos Gerais', 'state_id' => 13],
            ['name' => 'Cana Verde', 'state_id' => 13],
            ['name' => 'Canaã', 'state_id' => 13],
            ['name' => 'Canápolis', 'state_id' => 13],
            ['name' => 'Candeias', 'state_id' => 13],
            ['name' => 'Cantagalo', 'state_id' => 13],
            ['name' => 'Caparaó', 'state_id' => 13],
            ['name' => 'Capela Nova', 'state_id' => 13],
            ['name' => 'Capelinha', 'state_id' => 13],
            ['name' => 'Capetinga', 'state_id' => 13],
            ['name' => 'Capim Branco', 'state_id' => 13],
            ['name' => 'Capinópolis', 'state_id' => 13],
            ['name' => 'Capitão Andrade', 'state_id' => 13],
            ['name' => 'Capitão Enéas', 'state_id' => 13],
            ['name' => 'Capitólio', 'state_id' => 13],
            ['name' => 'Caputira', 'state_id' => 13],
            ['name' => 'Caraí', 'state_id' => 13],
            ['name' => 'Caranaíba', 'state_id' => 13],
            ['name' => 'Carandaí', 'state_id' => 13],
            ['name' => 'Carangola', 'state_id' => 13],
            ['name' => 'Caratinga', 'state_id' => 13],
            ['name' => 'Carbonita', 'state_id' => 13],
            ['name' => 'Careaçu', 'state_id' => 13],
            ['name' => 'Carlos Chagas', 'state_id' => 13],
            ['name' => 'Carmésia', 'state_id' => 13],
            ['name' => 'Carmo da Cachoeira', 'state_id' => 13],
            ['name' => 'Carmo da Mata', 'state_id' => 13],
            ['name' => 'Carmo de Minas', 'state_id' => 13],
            ['name' => 'Carmo do Cajuru', 'state_id' => 13],
            ['name' => 'Carmo do Paranaíba', 'state_id' => 13],
            ['name' => 'Carmo do Rio Claro', 'state_id' => 13],
            ['name' => 'Carmópolis de Minas', 'state_id' => 13],
            ['name' => 'Carneirinho', 'state_id' => 13],
            ['name' => 'Carrancas', 'state_id' => 13],
            ['name' => 'Carvalhópolis', 'state_id' => 13],
            ['name' => 'Carvalhos', 'state_id' => 13],
            ['name' => 'Casa Grande', 'state_id' => 13],
            ['name' => 'Cascalho Rico', 'state_id' => 13],
            ['name' => 'Cássia', 'state_id' => 13],
            ['name' => 'Cataguases', 'state_id' => 13],
            ['name' => 'Catas Altas', 'state_id' => 13],
            ['name' => 'Catas Altas da Noruega', 'state_id' => 13],
            ['name' => 'Catuji', 'state_id' => 13],
            ['name' => 'Catuti', 'state_id' => 13],
            ['name' => 'Caxambu', 'state_id' => 13],
            ['name' => 'Cedro do Abaeté', 'state_id' => 13],
            ['name' => 'Central de Minas', 'state_id' => 13],
            ['name' => 'Centralina', 'state_id' => 13],
            ['name' => 'Chácara', 'state_id' => 13],
            ['name' => 'Chalé', 'state_id' => 13],
            ['name' => 'Chapada do Norte', 'state_id' => 13],
            ['name' => 'Chapada Gaúcha', 'state_id' => 13],
            ['name' => 'Chiador', 'state_id' => 13],
            ['name' => 'Cipotânea', 'state_id' => 13],
            ['name' => 'Claraval', 'state_id' => 13],
            ['name' => 'Claro dos Poções', 'state_id' => 13],
            ['name' => 'Cláudio', 'state_id' => 13],
            ['name' => 'Coimbra', 'state_id' => 13],
            ['name' => 'Coluna', 'state_id' => 13],
            ['name' => 'Comendador Gomes', 'state_id' => 13],
            ['name' => 'Comercinho', 'state_id' => 13],
            ['name' => 'Conceição da Aparecida', 'state_id' => 13],
            ['name' => 'Conceição da Barra de Minas', 'state_id' => 13],
            ['name' => 'Conceição das Alagoas', 'state_id' => 13],
            ['name' => 'Conceição das Pedras', 'state_id' => 13],
            ['name' => 'Conceição de Ipanema', 'state_id' => 13],
            ['name' => 'Conceição do Mato Dentro', 'state_id' => 13],
            ['name' => 'Conceição do Pará', 'state_id' => 13],
            ['name' => 'Conceição do Rio Verde', 'state_id' => 13],
            ['name' => 'Conceição dos Ouros', 'state_id' => 13],
            ['name' => 'Cônego Marinho', 'state_id' => 13],
            ['name' => 'Confins', 'state_id' => 13],
            ['name' => 'Congonhal', 'state_id' => 13],
            ['name' => 'Congonhas', 'state_id' => 13],
            ['name' => 'Congonhas do Norte', 'state_id' => 13],
            ['name' => 'Conquista', 'state_id' => 13],
            ['name' => 'Conselheiro Lafaiete', 'state_id' => 13],
            ['name' => 'Conselheiro Pena', 'state_id' => 13],
            ['name' => 'Consolação', 'state_id' => 13],
            ['name' => 'Contagem', 'state_id' => 13],
            ['name' => 'Coqueiral', 'state_id' => 13],
            ['name' => 'Coração de Jesus', 'state_id' => 13],
            ['name' => 'Cordisburgo', 'state_id' => 13],
            ['name' => 'Cordislândia', 'state_id' => 13],
            ['name' => 'Corinto', 'state_id' => 13],
            ['name' => 'Coroaci', 'state_id' => 13],
            ['name' => 'Coromandel', 'state_id' => 13],
            ['name' => 'Coronel Fabriciano', 'state_id' => 13],
            ['name' => 'Coronel Murta', 'state_id' => 13],
            ['name' => 'Coronel Pacheco', 'state_id' => 13],
            ['name' => 'Coronel Xavier Chaves', 'state_id' => 13],
            ['name' => 'Córrego Danta', 'state_id' => 13],
            ['name' => 'Córrego do Bom Jesus', 'state_id' => 13],
            ['name' => 'Córrego Fundo', 'state_id' => 13],
            ['name' => 'Córrego Novo', 'state_id' => 13],
            ['name' => 'Couto de Magalhães de Minas', 'state_id' => 13],
            ['name' => 'Crisólita', 'state_id' => 13],
            ['name' => 'Cristais', 'state_id' => 13],
            ['name' => 'Cristália', 'state_id' => 13],
            ['name' => 'Cristiano Otoni', 'state_id' => 13],
            ['name' => 'Cristina', 'state_id' => 13],
            ['name' => 'Crucilândia', 'state_id' => 13],
            ['name' => 'Cruzeiro da Fortaleza', 'state_id' => 13],
            ['name' => 'Cruzília', 'state_id' => 13],
            ['name' => 'Cuparaque', 'state_id' => 13],
            ['name' => 'Curral de Dentro', 'state_id' => 13],
            ['name' => 'Curvelo', 'state_id' => 13],
            ['name' => 'Datas', 'state_id' => 13],
            ['name' => 'Delfim Moreira', 'state_id' => 13],
            ['name' => 'Delfinópolis', 'state_id' => 13],
            ['name' => 'Delta', 'state_id' => 13],
            ['name' => 'Descoberto', 'state_id' => 13],
            ['name' => 'Desterro de Entre Rios', 'state_id' => 13],
            ['name' => 'Desterro do Melo', 'state_id' => 13],
            ['name' => 'Diamantina', 'state_id' => 13],
            ['name' => 'Diogo de Vasconcelos', 'state_id' => 13],
            ['name' => 'Dionísio', 'state_id' => 13],
            ['name' => 'Divinésia', 'state_id' => 13],
            ['name' => 'Divino', 'state_id' => 13],
            ['name' => 'Divino das Laranjeiras', 'state_id' => 13],
            ['name' => 'Divinolândia de Minas', 'state_id' => 13],
            ['name' => 'Divinópolis', 'state_id' => 13],
            ['name' => 'Divisa Alegre', 'state_id' => 13],
            ['name' => 'Divisa Nova', 'state_id' => 13],
            ['name' => 'Divisópolis', 'state_id' => 13],
            ['name' => 'Dom Bosco', 'state_id' => 13],
            ['name' => 'Dom Cavati', 'state_id' => 13],
            ['name' => 'Dom Joaquim', 'state_id' => 13],
            ['name' => 'Dom Silvério', 'state_id' => 13],
            ['name' => 'Dom Viçoso', 'state_id' => 13],
            ['name' => 'Dona Eusébia', 'state_id' => 13],
            ['name' => 'Dores de Campos', 'state_id' => 13],
            ['name' => 'Dores de Guanhães', 'state_id' => 13],
            ['name' => 'Dores do Indaiá', 'state_id' => 13],
            ['name' => 'Dores do Turvo', 'state_id' => 13],
            ['name' => 'Doresópolis', 'state_id' => 13],
            ['name' => 'Douradoquara', 'state_id' => 13],
            ['name' => 'Durandé', 'state_id' => 13],
            ['name' => 'Elói Mendes', 'state_id' => 13],
            ['name' => 'Engenheiro Caldas', 'state_id' => 13],
            ['name' => 'Engenheiro Navarro', 'state_id' => 13],
            ['name' => 'Entre Folhas', 'state_id' => 13],
            ['name' => 'Entre Rios de Minas', 'state_id' => 13],
            ['name' => 'Ervália', 'state_id' => 13],
            ['name' => 'Esmeraldas', 'state_id' => 13],
            ['name' => 'Espera Feliz', 'state_id' => 13],
            ['name' => 'Espinosa', 'state_id' => 13],
            ['name' => 'Espírito Santo do Dourado', 'state_id' => 13],
            ['name' => 'Estiva', 'state_id' => 13],
            ['name' => 'Estrela Dalva', 'state_id' => 13],
            ['name' => 'Estrela do Indaiá', 'state_id' => 13],
            ['name' => 'Estrela do Sul', 'state_id' => 13],
            ['name' => 'Eugenópolis', 'state_id' => 13],
            ['name' => 'Ewbank da Câmara', 'state_id' => 13],
            ['name' => 'Extrema', 'state_id' => 13],
            ['name' => 'Fama', 'state_id' => 13],
            ['name' => 'Faria Lemos', 'state_id' => 13],
            ['name' => 'Felício dos Santos', 'state_id' => 13],
            ['name' => 'Felisburgo', 'state_id' => 13],
            ['name' => 'Felixlândia', 'state_id' => 13],
            ['name' => 'Fernandes Tourinho', 'state_id' => 13],
            ['name' => 'Ferros', 'state_id' => 13],
            ['name' => 'Fervedouro', 'state_id' => 13],
            ['name' => 'Florestal', 'state_id' => 13],
            ['name' => 'Formiga', 'state_id' => 13],
            ['name' => 'Formoso', 'state_id' => 13],
            ['name' => 'Fortaleza de Minas', 'state_id' => 13],
            ['name' => 'Fortuna de Minas', 'state_id' => 13],
            ['name' => 'Francisco Badaró', 'state_id' => 13],
            ['name' => 'Francisco Dumont', 'state_id' => 13],
            ['name' => 'Francisco Sá', 'state_id' => 13],
            ['name' => 'Franciscópolis', 'state_id' => 13],
            ['name' => 'Frei Gaspar', 'state_id' => 13],
            ['name' => 'Frei Inocêncio', 'state_id' => 13],
            ['name' => 'Frei Lagonegro', 'state_id' => 13],
            ['name' => 'Fronteira', 'state_id' => 13],
            ['name' => 'Fronteira dos Vales', 'state_id' => 13],
            ['name' => 'Fruta de Leite', 'state_id' => 13],
            ['name' => 'Frutal', 'state_id' => 13],
            ['name' => 'Funilândia', 'state_id' => 13],
            ['name' => 'Galiléia', 'state_id' => 13],
            ['name' => 'Gameleiras', 'state_id' => 13],
            ['name' => 'Glaucilândia', 'state_id' => 13],
            ['name' => 'Goiabeira', 'state_id' => 13],
            ['name' => 'Goianá', 'state_id' => 13],
            ['name' => 'Gonçalves', 'state_id' => 13],
            ['name' => 'Gonzaga', 'state_id' => 13],
            ['name' => 'Gouveia', 'state_id' => 13],
            ['name' => 'Governador Valadares', 'state_id' => 13],
            ['name' => 'Grão Mogol', 'state_id' => 13],
            ['name' => 'Grupiara', 'state_id' => 13],
            ['name' => 'Guanhães', 'state_id' => 13],
            ['name' => 'Guapé', 'state_id' => 13],
            ['name' => 'Guaraciaba', 'state_id' => 13],
            ['name' => 'Guaraciama', 'state_id' => 13],
            ['name' => 'Guaranésia', 'state_id' => 13],
            ['name' => 'Guarani', 'state_id' => 13],
            ['name' => 'Guarará', 'state_id' => 13],
            ['name' => 'Guarda-Mor', 'state_id' => 13],
            ['name' => 'Guaxupé', 'state_id' => 13],
            ['name' => 'Guidoval', 'state_id' => 13],
            ['name' => 'Guimarânia', 'state_id' => 13],
            ['name' => 'Guiricema', 'state_id' => 13],
            ['name' => 'Gurinhatã', 'state_id' => 13],
            ['name' => 'Heliodora', 'state_id' => 13],
            ['name' => 'Iapu', 'state_id' => 13],
            ['name' => 'Ibertioga', 'state_id' => 13],
            ['name' => 'Ibiá', 'state_id' => 13],
            ['name' => 'Ibiaí', 'state_id' => 13],
            ['name' => 'Ibiracatu', 'state_id' => 13],
            ['name' => 'Ibiraci', 'state_id' => 13],
            ['name' => 'Ibirité', 'state_id' => 13],
            ['name' => 'Ibitiúra de Minas', 'state_id' => 13],
            ['name' => 'Ibituruna', 'state_id' => 13],
            ['name' => 'Icaraí de Minas', 'state_id' => 13],
            ['name' => 'Igarapé', 'state_id' => 13],
            ['name' => 'Igaratinga', 'state_id' => 13],
            ['name' => 'Iguatama', 'state_id' => 13],
            ['name' => 'Ijaci', 'state_id' => 13],
            ['name' => 'Ilicínea', 'state_id' => 13],
            ['name' => 'Imbé de Minas', 'state_id' => 13],
            ['name' => 'Inconfidentes', 'state_id' => 13],
            ['name' => 'Indaiabira', 'state_id' => 13],
            ['name' => 'Indianópolis', 'state_id' => 13],
            ['name' => 'Ingaí', 'state_id' => 13],
            ['name' => 'Inhapim', 'state_id' => 13],
            ['name' => 'Inhaúma', 'state_id' => 13],
            ['name' => 'Inimutaba', 'state_id' => 13],
            ['name' => 'Ipaba', 'state_id' => 13],
            ['name' => 'Ipanema', 'state_id' => 13],
            ['name' => 'Ipatinga', 'state_id' => 13],
            ['name' => 'Ipiaçu', 'state_id' => 13],
            ['name' => 'Ipuiúna', 'state_id' => 13],
            ['name' => 'Iraí de Minas', 'state_id' => 13],
            ['name' => 'Itabira', 'state_id' => 13],
            ['name' => 'Itabirinha de Mantena', 'state_id' => 13],
            ['name' => 'Itabirito', 'state_id' => 13],
            ['name' => 'Itacambira', 'state_id' => 13],
            ['name' => 'Itacarambi', 'state_id' => 13],
            ['name' => 'Itaguara', 'state_id' => 13],
            ['name' => 'Itaipé', 'state_id' => 13],
            ['name' => 'Itajubá', 'state_id' => 13],
            ['name' => 'Itamarandiba', 'state_id' => 13],
            ['name' => 'Itamarati de Minas', 'state_id' => 13],
            ['name' => 'Itambacuri', 'state_id' => 13],
            ['name' => 'Itambé do Mato Dentro', 'state_id' => 13],
            ['name' => 'Itamogi', 'state_id' => 13],
            ['name' => 'Itamonte', 'state_id' => 13],
            ['name' => 'Itanhandu', 'state_id' => 13],
            ['name' => 'Itanhomi', 'state_id' => 13],
            ['name' => 'Itaobim', 'state_id' => 13],
            ['name' => 'Itapagipe', 'state_id' => 13],
            ['name' => 'Itapecerica', 'state_id' => 13],
            ['name' => 'Itapeva', 'state_id' => 13],
            ['name' => 'Itatiaiuçu', 'state_id' => 13],
            ['name' => 'Itaú de Minas', 'state_id' => 13],
            ['name' => 'Itaúna', 'state_id' => 13],
            ['name' => 'Itaverava', 'state_id' => 13],
            ['name' => 'Itinga', 'state_id' => 13],
            ['name' => 'Itueta', 'state_id' => 13],
            ['name' => 'Ituiutaba', 'state_id' => 13],
            ['name' => 'Itumirim', 'state_id' => 13],
            ['name' => 'Iturama', 'state_id' => 13],
            ['name' => 'Itutinga', 'state_id' => 13],
            ['name' => 'Jaboticatubas', 'state_id' => 13],
            ['name' => 'Jacinto', 'state_id' => 13],
            ['name' => 'Jacuí', 'state_id' => 13],
            ['name' => 'Jacutinga', 'state_id' => 13],
            ['name' => 'Jaguaraçu', 'state_id' => 13],
            ['name' => 'Jaíba', 'state_id' => 13],
            ['name' => 'Jampruca', 'state_id' => 13],
            ['name' => 'Janaúba', 'state_id' => 13],
            ['name' => 'Januária', 'state_id' => 13],
            ['name' => 'Japaraíba', 'state_id' => 13],
            ['name' => 'Japonvar', 'state_id' => 13],
            ['name' => 'Jeceaba', 'state_id' => 13],
            ['name' => 'Jenipapo de Minas', 'state_id' => 13],
            ['name' => 'Jequeri', 'state_id' => 13],
            ['name' => 'Jequitaí', 'state_id' => 13],
            ['name' => 'Jequitibá', 'state_id' => 13],
            ['name' => 'Jequitinhonha', 'state_id' => 13],
            ['name' => 'Jesuânia', 'state_id' => 13],
            ['name' => 'Joaíma', 'state_id' => 13],
            ['name' => 'Joanésia', 'state_id' => 13],
            ['name' => 'João Monlevade', 'state_id' => 13],
            ['name' => 'João Pinheiro', 'state_id' => 13],
            ['name' => 'Joaquim Felício', 'state_id' => 13],
            ['name' => 'Jordânia', 'state_id' => 13],
            ['name' => 'José Gonçalves de Minas', 'state_id' => 13],
            ['name' => 'José Raydan', 'state_id' => 13],
            ['name' => 'Josenópolis', 'state_id' => 13],
            ['name' => 'Juatuba', 'state_id' => 13],
            ['name' => 'Juiz de Fora', 'state_id' => 13],
            ['name' => 'Juramento', 'state_id' => 13],
            ['name' => 'Juruaia', 'state_id' => 13],
            ['name' => 'Juvenília', 'state_id' => 13],
            ['name' => 'Ladainha', 'state_id' => 13],
            ['name' => 'Lagamar', 'state_id' => 13],
            ['name' => 'Lagoa da Prata', 'state_id' => 13],
            ['name' => 'Lagoa dos Patos', 'state_id' => 13],
            ['name' => 'Lagoa Dourada', 'state_id' => 13],
            ['name' => 'Lagoa Formosa', 'state_id' => 13],
            ['name' => 'Lagoa Grande', 'state_id' => 13],
            ['name' => 'Lagoa Santa', 'state_id' => 13],
            ['name' => 'Lajinha', 'state_id' => 13],
            ['name' => 'Lambari', 'state_id' => 13],
            ['name' => 'Lamim', 'state_id' => 13],
            ['name' => 'Laranjal', 'state_id' => 13],
            ['name' => 'Lassance', 'state_id' => 13],
            ['name' => 'Lavras', 'state_id' => 13],
            ['name' => 'Leandro Ferreira', 'state_id' => 13],
            ['name' => 'Leme do Prado', 'state_id' => 13],
            ['name' => 'Leopoldina', 'state_id' => 13],
            ['name' => 'Liberdade', 'state_id' => 13],
            ['name' => 'Lima Duarte', 'state_id' => 13],
            ['name' => 'Limeira do Oeste', 'state_id' => 13],
            ['name' => 'Lontra', 'state_id' => 13],
            ['name' => 'Luisburgo', 'state_id' => 13],
            ['name' => 'Luislândia', 'state_id' => 13],
            ['name' => 'Luminárias', 'state_id' => 13],
            ['name' => 'Luz', 'state_id' => 13],
            ['name' => 'Machacalis', 'state_id' => 13],
            ['name' => 'Machado', 'state_id' => 13],
            ['name' => 'Madre de Deus de Minas', 'state_id' => 13],
            ['name' => 'Malacacheta', 'state_id' => 13],
            ['name' => 'Mamonas', 'state_id' => 13],
            ['name' => 'Manga', 'state_id' => 13],
            ['name' => 'Manhuaçu', 'state_id' => 13],
            ['name' => 'Manhumirim', 'state_id' => 13],
            ['name' => 'Mantena', 'state_id' => 13],
            ['name' => 'Mar de Espanha', 'state_id' => 13],
            ['name' => 'Maravilhas', 'state_id' => 13],
            ['name' => 'Maria da Fé', 'state_id' => 13],
            ['name' => 'Mariana', 'state_id' => 13],
            ['name' => 'Marilac', 'state_id' => 13],
            ['name' => 'Mário Campos', 'state_id' => 13],
            ['name' => 'Maripá de Minas', 'state_id' => 13],
            ['name' => 'Marliéria', 'state_id' => 13],
            ['name' => 'Marmelópolis', 'state_id' => 13],
            ['name' => 'Martinho Campos', 'state_id' => 13],
            ['name' => 'Martins Soares', 'state_id' => 13],
            ['name' => 'Mata Verde', 'state_id' => 13],
            ['name' => 'Materlândia', 'state_id' => 13],
            ['name' => 'Mateus Leme', 'state_id' => 13],
            ['name' => 'Mathias Lobato', 'state_id' => 13],
            ['name' => 'Matias Barbosa', 'state_id' => 13],
            ['name' => 'Matias Cardoso', 'state_id' => 13],
            ['name' => 'Matipó', 'state_id' => 13],
            ['name' => 'Mato Verde', 'state_id' => 13],
            ['name' => 'Matozinhos', 'state_id' => 13],
            ['name' => 'Matutina', 'state_id' => 13],
            ['name' => 'Medeiros', 'state_id' => 13],
            ['name' => 'Medina', 'state_id' => 13],
            ['name' => 'Mendes Pimentel', 'state_id' => 13],
            ['name' => 'Mercês', 'state_id' => 13],
            ['name' => 'Mesquita', 'state_id' => 13],
            ['name' => 'Minas Novas', 'state_id' => 13],
            ['name' => 'Minduri', 'state_id' => 13],
            ['name' => 'Mirabela', 'state_id' => 13],
            ['name' => 'Miradouro', 'state_id' => 13],
            ['name' => 'Miraí', 'state_id' => 13],
            ['name' => 'Miravânia', 'state_id' => 13],
            ['name' => 'Moeda', 'state_id' => 13],
            ['name' => 'Moema', 'state_id' => 13],
            ['name' => 'Monjolos', 'state_id' => 13],
            ['name' => 'Monsenhor Paulo', 'state_id' => 13],
            ['name' => 'Montalvânia', 'state_id' => 13],
            ['name' => 'Monte Alegre de Minas', 'state_id' => 13],
            ['name' => 'Monte Azul', 'state_id' => 13],
            ['name' => 'Monte Belo', 'state_id' => 13],
            ['name' => 'Monte Carmelo', 'state_id' => 13],
            ['name' => 'Monte Formoso', 'state_id' => 13],
            ['name' => 'Monte Santo de Minas', 'state_id' => 13],
            ['name' => 'Monte Sião', 'state_id' => 13]
        ]);

        DB::table('cities')->insert([
            ['name' => 'Montes Claros', 'state_id' => 13],
            ['name' => 'Montezuma', 'state_id' => 13],
            ['name' => 'Morada Nova de Minas', 'state_id' => 13],
            ['name' => 'Morro da Garça', 'state_id' => 13],
            ['name' => 'Morro do Pilar', 'state_id' => 13],
            ['name' => 'Munhoz', 'state_id' => 13],
            ['name' => 'Muriaé', 'state_id' => 13],
            ['name' => 'Mutum', 'state_id' => 13],
            ['name' => 'Muzambinho', 'state_id' => 13],
            ['name' => 'Nacip Raydan', 'state_id' => 13],
            ['name' => 'Nanuque', 'state_id' => 13],
            ['name' => 'Naque', 'state_id' => 13],
            ['name' => 'Natalândia', 'state_id' => 13],
            ['name' => 'Natércia', 'state_id' => 13],
            ['name' => 'Nazareno', 'state_id' => 13],
            ['name' => 'Nepomuceno', 'state_id' => 13],
            ['name' => 'Ninheira', 'state_id' => 13],
            ['name' => 'Nova Belém', 'state_id' => 13],
            ['name' => 'Nova Era', 'state_id' => 13],
            ['name' => 'Nova Lima', 'state_id' => 13],
            ['name' => 'Nova Módica', 'state_id' => 13],
            ['name' => 'Nova Ponte', 'state_id' => 13],
            ['name' => 'Nova Porteirinha', 'state_id' => 13],
            ['name' => 'Nova Resende', 'state_id' => 13],
            ['name' => 'Nova Serrana', 'state_id' => 13],
            ['name' => 'Nova União', 'state_id' => 13],
            ['name' => 'Novo Cruzeiro', 'state_id' => 13],
            ['name' => 'Novo Oriente de Minas', 'state_id' => 13],
            ['name' => 'Novorizonte', 'state_id' => 13],
            ['name' => 'Olaria', 'state_id' => 13],
            ['name' => 'Olhos-d`Água', 'state_id' => 13],
            ['name' => 'Olímpio Noronha', 'state_id' => 13],
            ['name' => 'Oliveira', 'state_id' => 13],
            ['name' => 'Oliveira Fortes', 'state_id' => 13],
            ['name' => 'Onça de Pitangui', 'state_id' => 13],
            ['name' => 'Oratórios', 'state_id' => 13],
            ['name' => 'Orizânia', 'state_id' => 13],
            ['name' => 'Ouro Branco', 'state_id' => 13],
            ['name' => 'Ouro Fino', 'state_id' => 13],
            ['name' => 'Ouro Preto', 'state_id' => 13],
            ['name' => 'Ouro Verde de Minas', 'state_id' => 13],
            ['name' => 'Padre Carvalho', 'state_id' => 13],
            ['name' => 'Padre Paraíso', 'state_id' => 13],
            ['name' => 'Pai Pedro', 'state_id' => 13],
            ['name' => 'Paineiras', 'state_id' => 13],
            ['name' => 'Pains', 'state_id' => 13],
            ['name' => 'Paiva', 'state_id' => 13],
            ['name' => 'Palma', 'state_id' => 13],
            ['name' => 'Palmópolis', 'state_id' => 13],
            ['name' => 'Papagaios', 'state_id' => 13],
            ['name' => 'Pará de Minas', 'state_id' => 13],
            ['name' => 'Paracatu', 'state_id' => 13],
            ['name' => 'Paraguaçu', 'state_id' => 13],
            ['name' => 'Paraisópolis', 'state_id' => 13],
            ['name' => 'Paraopeba', 'state_id' => 13],
            ['name' => 'Passa Quatro', 'state_id' => 13],
            ['name' => 'Passa Tempo', 'state_id' => 13],
            ['name' => 'Passabém', 'state_id' => 13],
            ['name' => 'Passa-Vinte', 'state_id' => 13],
            ['name' => 'Passos', 'state_id' => 13],
            ['name' => 'Patis', 'state_id' => 13],
            ['name' => 'Patos de Minas', 'state_id' => 13],
            ['name' => 'Patrocínio', 'state_id' => 13],
            ['name' => 'Patrocínio do Muriaé', 'state_id' => 13],
            ['name' => 'Paula Cândido', 'state_id' => 13],
            ['name' => 'Paulistas', 'state_id' => 13],
            ['name' => 'Pavão', 'state_id' => 13],
            ['name' => 'Peçanha', 'state_id' => 13],
            ['name' => 'Pedra Azul', 'state_id' => 13],
            ['name' => 'Pedra Bonita', 'state_id' => 13],
            ['name' => 'Pedra do Anta', 'state_id' => 13],
            ['name' => 'Pedra do Indaiá', 'state_id' => 13],
            ['name' => 'Pedra Dourada', 'state_id' => 13],
            ['name' => 'Pedralva', 'state_id' => 13],
            ['name' => 'Pedras de Maria da Cruz', 'state_id' => 13],
            ['name' => 'Pedrinópolis', 'state_id' => 13],
            ['name' => 'Pedro Leopoldo', 'state_id' => 13],
            ['name' => 'Pedro Teixeira', 'state_id' => 13],
            ['name' => 'Pequeri', 'state_id' => 13],
            ['name' => 'Pequi', 'state_id' => 13],
            ['name' => 'Perdigão', 'state_id' => 13],
            ['name' => 'Perdizes', 'state_id' => 13],
            ['name' => 'Perdões', 'state_id' => 13],
            ['name' => 'Periquito', 'state_id' => 13],
            ['name' => 'Pescador', 'state_id' => 13],
            ['name' => 'Piau', 'state_id' => 13],
            ['name' => 'Piedade de Caratinga', 'state_id' => 13],
            ['name' => 'Piedade de Ponte Nova', 'state_id' => 13],
            ['name' => 'Piedade do Rio Grande', 'state_id' => 13],
            ['name' => 'Piedade dos Gerais', 'state_id' => 13],
            ['name' => 'Pimenta', 'state_id' => 13],
            ['name' => 'Pingo-d`Água', 'state_id' => 13],
            ['name' => 'Pintópolis', 'state_id' => 13],
            ['name' => 'Piracema', 'state_id' => 13],
            ['name' => 'Pirajuba', 'state_id' => 13],
            ['name' => 'Piranga', 'state_id' => 13],
            ['name' => 'Piranguçu', 'state_id' => 13],
            ['name' => 'Piranguinho', 'state_id' => 13],
            ['name' => 'Pirapetinga', 'state_id' => 13],
            ['name' => 'Pirapora', 'state_id' => 13],
            ['name' => 'Piraúba', 'state_id' => 13],
            ['name' => 'Pitangui', 'state_id' => 13],
            ['name' => 'Piumhi', 'state_id' => 13],
            ['name' => 'Planura', 'state_id' => 13],
            ['name' => 'Poço Fundo', 'state_id' => 13],
            ['name' => 'Poços de Caldas', 'state_id' => 13],
            ['name' => 'Pocrane', 'state_id' => 13],
            ['name' => 'Pompéu', 'state_id' => 13],
            ['name' => 'Ponte Nova', 'state_id' => 13],
            ['name' => 'Ponto Chique', 'state_id' => 13],
            ['name' => 'Ponto dos Volantes', 'state_id' => 13],
            ['name' => 'Porteirinha', 'state_id' => 13],
            ['name' => 'Porto Firme', 'state_id' => 13],
            ['name' => 'Poté', 'state_id' => 13],
            ['name' => 'Pouso Alegre', 'state_id' => 13],
            ['name' => 'Pouso Alto', 'state_id' => 13],
            ['name' => 'Prados', 'state_id' => 13],
            ['name' => 'Prata', 'state_id' => 13],
            ['name' => 'Pratápolis', 'state_id' => 13],
            ['name' => 'Pratinha', 'state_id' => 13],
            ['name' => 'Presidente Bernardes', 'state_id' => 13],
            ['name' => 'Presidente Juscelino', 'state_id' => 13],
            ['name' => 'Presidente Kubitschek', 'state_id' => 13],
            ['name' => 'Presidente Olegário', 'state_id' => 13],
            ['name' => 'Prudente de Morais', 'state_id' => 13],
            ['name' => 'Quartel Geral', 'state_id' => 13],
            ['name' => 'Queluzito', 'state_id' => 13],
            ['name' => 'Raposos', 'state_id' => 13],
            ['name' => 'Raul Soares', 'state_id' => 13],
            ['name' => 'Recreio', 'state_id' => 13],
            ['name' => 'Reduto', 'state_id' => 13],
            ['name' => 'Resende Costa', 'state_id' => 13],
            ['name' => 'Resplendor', 'state_id' => 13],
            ['name' => 'Ressaquinha', 'state_id' => 13],
            ['name' => 'Riachinho', 'state_id' => 13],
            ['name' => 'Riacho dos Machados', 'state_id' => 13],
            ['name' => 'Ribeirão das Neves', 'state_id' => 13],
            ['name' => 'Ribeirão Vermelho', 'state_id' => 13],
            ['name' => 'Rio Acima', 'state_id' => 13],
            ['name' => 'Rio Casca', 'state_id' => 13],
            ['name' => 'Rio do Prado', 'state_id' => 13],
            ['name' => 'Rio Doce', 'state_id' => 13],
            ['name' => 'Rio Espera', 'state_id' => 13],
            ['name' => 'Rio Manso', 'state_id' => 13],
            ['name' => 'Rio Novo', 'state_id' => 13],
            ['name' => 'Rio Paranaíba', 'state_id' => 13],
            ['name' => 'Rio Pardo de Minas', 'state_id' => 13],
            ['name' => 'Rio Piracicaba', 'state_id' => 13],
            ['name' => 'Rio Pomba', 'state_id' => 13],
            ['name' => 'Rio Preto', 'state_id' => 13],
            ['name' => 'Rio Vermelho', 'state_id' => 13],
            ['name' => 'Ritápolis', 'state_id' => 13],
            ['name' => 'Rochedo de Minas', 'state_id' => 13],
            ['name' => 'Rodeiro', 'state_id' => 13],
            ['name' => 'Romaria', 'state_id' => 13],
            ['name' => 'Rosário da Limeira', 'state_id' => 13],
            ['name' => 'Rubelita', 'state_id' => 13],
            ['name' => 'Rubim', 'state_id' => 13],
            ['name' => 'Sabará', 'state_id' => 13],
            ['name' => 'Sabinópolis', 'state_id' => 13],
            ['name' => 'Sacramento', 'state_id' => 13],
            ['name' => 'Salinas', 'state_id' => 13],
            ['name' => 'Salto da Divisa', 'state_id' => 13],
            ['name' => 'Santa Bárbara', 'state_id' => 13],
            ['name' => 'Santa Bárbara do Leste', 'state_id' => 13],
            ['name' => 'Santa Bárbara do Monte Verde', 'state_id' => 13],
            ['name' => 'Santa Bárbara do Tugúrio', 'state_id' => 13],
            ['name' => 'Santa Cruz de Minas', 'state_id' => 13],
            ['name' => 'Santa Cruz de Salinas', 'state_id' => 13],
            ['name' => 'Santa Cruz do Escalvado', 'state_id' => 13],
            ['name' => 'Santa Efigênia de Minas', 'state_id' => 13],
            ['name' => 'Santa Fé de Minas', 'state_id' => 13],
            ['name' => 'Santa Helena de Minas', 'state_id' => 13],
            ['name' => 'Santa Juliana', 'state_id' => 13],
            ['name' => 'Santa Luzia', 'state_id' => 13],
            ['name' => 'Santa Margarida', 'state_id' => 13],
            ['name' => 'Santa Maria de Itabira', 'state_id' => 13],
            ['name' => 'Santa Maria do Salto', 'state_id' => 13],
            ['name' => 'Santa Maria do Suaçuí', 'state_id' => 13],
            ['name' => 'Santa Rita de Caldas', 'state_id' => 13],
            ['name' => 'Santa Rita de Ibitipoca', 'state_id' => 13],
            ['name' => 'Santa Rita de Jacutinga', 'state_id' => 13],
            ['name' => 'Santa Rita de Minas', 'state_id' => 13],
            ['name' => 'Santa Rita do Itueto', 'state_id' => 13],
            ['name' => 'Santa Rita do Sapucaí', 'state_id' => 13],
            ['name' => 'Santa Rosa da Serra', 'state_id' => 13],
            ['name' => 'Santa Vitória', 'state_id' => 13],
            ['name' => 'Santana da Vargem', 'state_id' => 13],
            ['name' => 'Santana de Cataguases', 'state_id' => 13],
            ['name' => 'Santana de Pirapama', 'state_id' => 13],
            ['name' => 'Santana do Deserto', 'state_id' => 13],
            ['name' => 'Santana do Garambéu', 'state_id' => 13],
            ['name' => 'Santana do Jacaré', 'state_id' => 13],
            ['name' => 'Santana do Manhuaçu', 'state_id' => 13],
            ['name' => 'Santana do Paraíso', 'state_id' => 13],
            ['name' => 'Santana do Riacho', 'state_id' => 13],
            ['name' => 'Santana dos Montes', 'state_id' => 13],
            ['name' => 'Santo Antônio do Amparo', 'state_id' => 13],
            ['name' => 'Santo Antônio do Aventureiro', 'state_id' => 13],
            ['name' => 'Santo Antônio do Grama', 'state_id' => 13],
            ['name' => 'Santo Antônio do Itambé', 'state_id' => 13],
            ['name' => 'Santo Antônio do Jacinto', 'state_id' => 13],
            ['name' => 'Santo Antônio do Monte', 'state_id' => 13],
            ['name' => 'Santo Antônio do Retiro', 'state_id' => 13],
            ['name' => 'Santo Antônio do Rio Abaixo', 'state_id' => 13],
            ['name' => 'Santo Hipólito', 'state_id' => 13],
            ['name' => 'Santos Dumont', 'state_id' => 13],
            ['name' => 'São Bento Abade', 'state_id' => 13],
            ['name' => 'São Brás do Suaçuí', 'state_id' => 13],
            ['name' => 'São Domingos das Dores', 'state_id' => 13],
            ['name' => 'São Domingos do Prata', 'state_id' => 13],
            ['name' => 'São Félix de Minas', 'state_id' => 13],
            ['name' => 'São Francisco', 'state_id' => 13],
            ['name' => 'São Francisco de Paula', 'state_id' => 13],
            ['name' => 'São Francisco de Sales', 'state_id' => 13],
            ['name' => 'São Francisco do Glória', 'state_id' => 13],
            ['name' => 'São Geraldo', 'state_id' => 13],
            ['name' => 'São Geraldo da Piedade', 'state_id' => 13],
            ['name' => 'São Geraldo do Baixio', 'state_id' => 13],
            ['name' => 'São Gonçalo do Abaeté', 'state_id' => 13],
            ['name' => 'São Gonçalo do Pará', 'state_id' => 13],
            ['name' => 'São Gonçalo do Rio Abaixo', 'state_id' => 13],
            ['name' => 'São Gonçalo do Rio Preto', 'state_id' => 13],
            ['name' => 'São Gonçalo do Sapucaí', 'state_id' => 13],
            ['name' => 'São Gotardo', 'state_id' => 13],
            ['name' => 'São João Batista do Glória', 'state_id' => 13],
            ['name' => 'São João da Lagoa', 'state_id' => 13],
            ['name' => 'São João da Mata', 'state_id' => 13],
            ['name' => 'São João da Ponte', 'state_id' => 13],
            ['name' => 'São João das Missões', 'state_id' => 13],
            ['name' => 'São João del Rei', 'state_id' => 13],
            ['name' => 'São João do Manhuaçu', 'state_id' => 13],
            ['name' => 'São João do Manteninha', 'state_id' => 13],
            ['name' => 'São João do Oriente', 'state_id' => 13],
            ['name' => 'São João do Pacuí', 'state_id' => 13],
            ['name' => 'São João do Paraíso', 'state_id' => 13],
            ['name' => 'São João Evangelista', 'state_id' => 13],
            ['name' => 'São João Nepomuceno', 'state_id' => 13],
            ['name' => 'São Joaquim de Bicas', 'state_id' => 13],
            ['name' => 'São José da Barra', 'state_id' => 13],
            ['name' => 'São José da Lapa', 'state_id' => 13],
            ['name' => 'São José da Safira', 'state_id' => 13],
            ['name' => 'São José da Varginha', 'state_id' => 13],
            ['name' => 'São José do Alegre', 'state_id' => 13],
            ['name' => 'São José do Divino', 'state_id' => 13],
            ['name' => 'São José do Goiabal', 'state_id' => 13],
            ['name' => 'São José do Jacuri', 'state_id' => 13],
            ['name' => 'São José do Mantimento', 'state_id' => 13],
            ['name' => 'São Lourenço', 'state_id' => 13],
            ['name' => 'São Miguel do Anta', 'state_id' => 13],
            ['name' => 'São Pedro da União', 'state_id' => 13],
            ['name' => 'São Pedro do Suaçuí', 'state_id' => 13],
            ['name' => 'São Pedro dos Ferros', 'state_id' => 13],
            ['name' => 'São Romão', 'state_id' => 13],
            ['name' => 'São Roque de Minas', 'state_id' => 13],
            ['name' => 'São Sebastião da Bela Vista', 'state_id' => 13],
            ['name' => 'São Sebastião da Vargem Alegre', 'state_id' => 13],
            ['name' => 'São Sebastião do Anta', 'state_id' => 13],
            ['name' => 'São Sebastião do Maranhão', 'state_id' => 13],
            ['name' => 'São Sebastião do Oeste', 'state_id' => 13],
            ['name' => 'São Sebastião do Paraíso', 'state_id' => 13],
            ['name' => 'São Sebastião do Rio Preto', 'state_id' => 13],
            ['name' => 'São Sebastião do Rio Verde', 'state_id' => 13],
            ['name' => 'São Thomé das Letras', 'state_id' => 13],
            ['name' => 'São Tiago', 'state_id' => 13],
            ['name' => 'São Tomás de Aquino', 'state_id' => 13],
            ['name' => 'São Vicente de Minas', 'state_id' => 13],
            ['name' => 'Sapucaí-Mirim', 'state_id' => 13],
            ['name' => 'Sardoá', 'state_id' => 13],
            ['name' => 'Sarzedo', 'state_id' => 13],
            ['name' => 'Sem-Peixe', 'state_id' => 13],
            ['name' => 'Senador Amaral', 'state_id' => 13],
            ['name' => 'Senador Cortes', 'state_id' => 13],
            ['name' => 'Senador Firmino', 'state_id' => 13],
            ['name' => 'Senador José Bento', 'state_id' => 13],
            ['name' => 'Senador Modestino Gonçalves', 'state_id' => 13],
            ['name' => 'Senhora de Oliveira', 'state_id' => 13],
            ['name' => 'Senhora do Porto', 'state_id' => 13],
            ['name' => 'Senhora dos Remédios', 'state_id' => 13],
            ['name' => 'Sericita', 'state_id' => 13],
            ['name' => 'Seritinga', 'state_id' => 13],
            ['name' => 'Serra Azul de Minas', 'state_id' => 13],
            ['name' => 'Serra da Saudade', 'state_id' => 13],
            ['name' => 'Serra do Salitre', 'state_id' => 13],
            ['name' => 'Serra dos Aimorés', 'state_id' => 13],
            ['name' => 'Serrania', 'state_id' => 13],
            ['name' => 'Serranópolis de Minas', 'state_id' => 13],
            ['name' => 'Serranos', 'state_id' => 13],
            ['name' => 'Serro', 'state_id' => 13],
            ['name' => 'Sete Lagoas', 'state_id' => 13],
            ['name' => 'Setubinha', 'state_id' => 13],
            ['name' => 'Silveirânia', 'state_id' => 13],
            ['name' => 'Silvianópolis', 'state_id' => 13],
            ['name' => 'Simão Pereira', 'state_id' => 13],
            ['name' => 'Simonésia', 'state_id' => 13],
            ['name' => 'Sobrália', 'state_id' => 13],
            ['name' => 'Soledade de Minas', 'state_id' => 13],
            ['name' => 'Tabuleiro', 'state_id' => 13],
            ['name' => 'Taiobeiras', 'state_id' => 13],
            ['name' => 'Taparuba', 'state_id' => 13],
            ['name' => 'Tapira', 'state_id' => 13],
            ['name' => 'Tapiraí', 'state_id' => 13],
            ['name' => 'Taquaraçu de Minas', 'state_id' => 13],
            ['name' => 'Tarumirim', 'state_id' => 13],
            ['name' => 'Teixeiras', 'state_id' => 13],
            ['name' => 'Teófilo Otoni', 'state_id' => 13],
            ['name' => 'Timóteo', 'state_id' => 13],
            ['name' => 'Tiradentes', 'state_id' => 13],
            ['name' => 'Tiros', 'state_id' => 13],
            ['name' => 'Tocantins', 'state_id' => 13],
            ['name' => 'Tocos do Moji', 'state_id' => 13],
            ['name' => 'Toledo', 'state_id' => 13],
            ['name' => 'Tombos', 'state_id' => 13],
            ['name' => 'Três Corações', 'state_id' => 13],
            ['name' => 'Três Marias', 'state_id' => 13],
            ['name' => 'Três Pontas', 'state_id' => 13],
            ['name' => 'Tumiritinga', 'state_id' => 13],
            ['name' => 'Tupaciguara', 'state_id' => 13],
            ['name' => 'Turmalina', 'state_id' => 13],
            ['name' => 'Turvolândia', 'state_id' => 13],
            ['name' => 'Ubá', 'state_id' => 13],
            ['name' => 'Ubaí', 'state_id' => 13],
            ['name' => 'Ubaporanga', 'state_id' => 13],
            ['name' => 'Uberaba', 'state_id' => 13],
            ['name' => 'Uberlândia', 'state_id' => 13],
            ['name' => 'Umburatiba', 'state_id' => 13],
            ['name' => 'Unaí', 'state_id' => 13],
            ['name' => 'União de Minas', 'state_id' => 13],
            ['name' => 'Uruana de Minas', 'state_id' => 13],
            ['name' => 'Urucânia', 'state_id' => 13],
            ['name' => 'Urucuia', 'state_id' => 13],
            ['name' => 'Vargem Alegre', 'state_id' => 13],
            ['name' => 'Vargem Bonita', 'state_id' => 13],
            ['name' => 'Vargem Grande do Rio Pardo', 'state_id' => 13],
            ['name' => 'Varginha', 'state_id' => 13],
            ['name' => 'Varjão de Minas', 'state_id' => 13],
            ['name' => 'Várzea da Palma', 'state_id' => 13],
            ['name' => 'Varzelândia', 'state_id' => 13],
            ['name' => 'Vazante', 'state_id' => 13],
            ['name' => 'Verdelândia', 'state_id' => 13],
            ['name' => 'Veredinha', 'state_id' => 13],
            ['name' => 'Veríssimo', 'state_id' => 13],
            ['name' => 'Vermelho Novo', 'state_id' => 13],
            ['name' => 'Vespasiano', 'state_id' => 13],
            ['name' => 'Viçosa', 'state_id' => 13],
            ['name' => 'Vieiras', 'state_id' => 13],
            ['name' => 'Virgem da Lapa', 'state_id' => 13],
            ['name' => 'Virgínia', 'state_id' => 13],
            ['name' => 'Virginópolis', 'state_id' => 13],
            ['name' => 'Virgolândia', 'state_id' => 13],
            ['name' => 'Visconde do Rio Branco', 'state_id' => 13],
            ['name' => 'Volta Grande', 'state_id' => 13],
            ['name' => 'Wenceslau Braz', 'state_id' => 13]
        ]);

        $this->command->info('Cidades de Minas Gerais importadas com sucesso!');
    }
}