<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesAlagoasSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
            ['name' => 'Água Branca', 'state_id' => 2],
            ['name' => 'Anadia', 'state_id' => 2],
            ['name' => 'Arapiraca', 'state_id' => 2],
            ['name' => 'Atalaia', 'state_id' => 2],
            ['name' => 'Barra de Santo Antônio', 'state_id' => 2],
            ['name' => 'Barra de São Miguel', 'state_id' => 2],
            ['name' => 'Batalha', 'state_id' => 2],
            ['name' => 'Belém', 'state_id' => 2],
            ['name' => 'Belo Monte', 'state_id' => 2],
            ['name' => 'Boca da Mata', 'state_id' => 2],
            ['name' => 'Branquinha', 'state_id' => 2],
            ['name' => 'Cacimbinhas', 'state_id' => 2],
            ['name' => 'Cajueiro', 'state_id' => 2],
            ['name' => 'Campestre', 'state_id' => 2],
            ['name' => 'Campo Alegre', 'state_id' => 2],
            ['name' => 'Campo Grande', 'state_id' => 2],
            ['name' => 'Canapi', 'state_id' => 2],
            ['name' => 'Capela', 'state_id' => 2],
            ['name' => 'Carneiros', 'state_id' => 2],
            ['name' => 'Chã Preta', 'state_id' => 2],
            ['name' => 'Coité do Nóia', 'state_id' => 2],
            ['name' => 'Colônia Leopoldina', 'state_id' => 2],
            ['name' => 'Coqueiro Seco', 'state_id' => 2],
            ['name' => 'Coruripe', 'state_id' => 2],
            ['name' => 'Craíbas', 'state_id' => 2],
            ['name' => 'Delmiro Gouveia', 'state_id' => 2],
            ['name' => 'Dois Riachos', 'state_id' => 2],
            ['name' => 'Estrela de Alagoas', 'state_id' => 2],
            ['name' => 'Feira Grande', 'state_id' => 2],
            ['name' => 'Feliz Deserto', 'state_id' => 2],
            ['name' => 'Flexeiras', 'state_id' => 2],
            ['name' => 'Girau do Ponciano', 'state_id' => 2],
            ['name' => 'Ibateguara', 'state_id' => 2],
            ['name' => 'Igaci', 'state_id' => 2],
            ['name' => 'Igreja Nova', 'state_id' => 2],
            ['name' => 'Inhapi', 'state_id' => 2],
            ['name' => 'Jacaré dos Homens', 'state_id' => 2],
            ['name' => 'Jacuípe', 'state_id' => 2],
            ['name' => 'Japaratinga', 'state_id' => 2],
            ['name' => 'Jaramataia', 'state_id' => 2],
            ['name' => 'Jequiá da Praia', 'state_id' => 2],
            ['name' => 'Joaquim Gomes', 'state_id' => 2],
            ['name' => 'Jundiá', 'state_id' => 2],
            ['name' => 'Junqueiro', 'state_id' => 2],
            ['name' => 'Lagoa da Canoa', 'state_id' => 2],
            ['name' => 'Limoeiro de Anadia', 'state_id' => 2],
            ['name' => 'Maceió', 'state_id' => 2],
            ['name' => 'Major Isidoro', 'state_id' => 2],
            ['name' => 'Mar Vermelho', 'state_id' => 2],
            ['name' => 'Maragogi', 'state_id' => 2],
            ['name' => 'Maravilha', 'state_id' => 2],
            ['name' => 'Marechal Deodoro', 'state_id' => 2],
            ['name' => 'Maribondo', 'state_id' => 2],
            ['name' => 'Mata Grande', 'state_id' => 2],
            ['name' => 'Matriz de Camaragibe', 'state_id' => 2],
            ['name' => 'Messias', 'state_id' => 2],
            ['name' => 'Minador do Negrão', 'state_id' => 2],
            ['name' => 'Monteirópolis', 'state_id' => 2],
            ['name' => 'Murici', 'state_id' => 2],
            ['name' => 'Novo Lino', 'state_id' => 2],
            ['name' => 'Olho d`Água das Flores', 'state_id' => 2],
            ['name' => 'Olho d`Água do Casado', 'state_id' => 2],
            ['name' => 'Olho d`Água Grande', 'state_id' => 2],
            ['name' => 'Olivença', 'state_id' => 2],
            ['name' => 'Ouro Branco', 'state_id' => 2],
            ['name' => 'Palestina', 'state_id' => 2],
            ['name' => 'Palmeira dos Índios', 'state_id' => 2],
            ['name' => 'Pão de Açúcar', 'state_id' => 2],
            ['name' => 'Pariconha', 'state_id' => 2],
            ['name' => 'Paripueira', 'state_id' => 2],
            ['name' => 'Passo de Camaragibe', 'state_id' => 2],
            ['name' => 'Paulo Jacinto', 'state_id' => 2],
            ['name' => 'Penedo', 'state_id' => 2],
            ['name' => 'Piaçabuçu', 'state_id' => 2],
            ['name' => 'Pilar', 'state_id' => 2],
            ['name' => 'Pindoba', 'state_id' => 2],
            ['name' => 'Piranhas', 'state_id' => 2],
            ['name' => 'Poço das Trincheiras', 'state_id' => 2],
            ['name' => 'Porto Calvo', 'state_id' => 2],
            ['name' => 'Porto de Pedras', 'state_id' => 2],
            ['name' => 'Porto Real do Colégio', 'state_id' => 2],
            ['name' => 'Quebrangulo', 'state_id' => 2],
            ['name' => 'Rio Largo', 'state_id' => 2],
            ['name' => 'Roteiro', 'state_id' => 2],
            ['name' => 'Santa Luzia do Norte', 'state_id' => 2],
            ['name' => 'Santana do Ipanema', 'state_id' => 2],
            ['name' => 'Santana do Mundaú', 'state_id' => 2],
            ['name' => 'São Brás', 'state_id' => 2],
            ['name' => 'São José da Laje', 'state_id' => 2],
            ['name' => 'São José da Tapera', 'state_id' => 2],
            ['name' => 'São Luís do Quitunde', 'state_id' => 2],
            ['name' => 'São Miguel dos Campos', 'state_id' => 2],
            ['name' => 'São Miguel dos Milagres', 'state_id' => 2],
            ['name' => 'São Sebastião', 'state_id' => 2],
            ['name' => 'Satuba', 'state_id' => 2],
            ['name' => 'Senador Rui Palmeira', 'state_id' => 2],
            ['name' => 'Tanque d`Arca', 'state_id' => 2],
            ['name' => 'Taquarana', 'state_id' => 2],
            ['name' => 'Teotônio Vilela', 'state_id' => 2],
            ['name' => 'Traipu', 'state_id' => 2],
            ['name' => 'União dos Palmares', 'state_id' => 2],
            ['name' => 'Viçosa', 'state_id' => 2]
        ]);

        $this->command->info('Cidades do Alagoas importadas com sucesso!');
    }
}